### ISSUE TITLE
All scrips with "_" are duplicated

### ISSUE THREAD

**Issue by MeisterTR** [nokxs/iobroker-javascript-vs-code-extension#17] opened 2021-01-29 20:20 UTC
i saved all my scrips with _ e.g "test_licht" in the extention is everything ok, but in my js adapter the files are duplicated one with "test_licht" and one "test licht" both get the changes from vs

**Comment by nokxs** [comment] 2021-01-30 16:31
I was able to reproduce this behaviour. It will be fixed with the next release, but this may take a while, because I'm currently doing a big refactoring.

**Closed as completed** 2021-02-13 14:20 UTC
Labels: bug
